const mongoose = require("mongoose");
const User = require("./models/User");
const Drink = require("./models/Drink");
const connectDB = require("./config/database");

const initializeDatabase = async () => {
  try {
    console.log("Connecting to database...");
    // Connect to database
    await connectDB();
    console.log("Connected to database successfully!");

    // Clear existing data
    console.log("Clearing existing data...");
    await User.deleteMany({});
    await Drink.deleteMany({});
    console.log("Existing data cleared successfully!");

    // Create admin user
    console.log("Creating admin user...");
    // Create admin user
    const adminUser = await User.create({
      name: "Admin",
      email: "admin@eclipse.com",
      password: "admin123456",
      role: "admin",
      isEmailVerified: true,
      isActive: true,
    });

    console.log("Admin user created successfully");

    // Sample drinks data
    const drinks = [
      {
        name: "Cà phê sữa đá",
        description:
          "Cà phê phin truyền thống kết hợp với sữa đặc tạo nên hương vị đậm đà, hài hòa",
        price: 29000,
        category: "coffee",
        size: ["S", "M", "L"],
        temperature: ["cold"],
        sweetness: ["none", "low", "normal"],
        ingredients: ["Cà phê", "Sữa đặc"],
        images: ["1752854247128-317889868.webp"], // Sử dụng tên file có sẵn trong uploads
        stock: 100,
        isAvailable: true,
        preparationTime: 3,
        calories: 150,
        isFeatured: true,
        createdBy: adminUser._id,
      },
      {
        name: "Trà sen vàng",
        description: "Trà ướp hương sen thanh mát, tinh tế và thơm lừng",
        price: 39000,
        category: "tea",
        size: ["M", "L"],
        temperature: ["hot", "cold"],
        sweetness: ["none", "low", "normal", "high"],
        ingredients: ["Trà", "Hương sen", "Mật ong"],
        images: ["1752854247138-556146158.webp"], // Sử dụng tên file có sẵn
        stock: 100,
        isAvailable: true,
        preparationTime: 5,
        calories: 90,
        isFeatured: true,
        createdBy: adminUser._id,
      },
      {
        name: "Matcha Latte",
        description: "Bột trà xanh Matcha thượng hạng kết hợp với sữa tươi",
        price: 45000,
        category: "matcha",
        size: ["M", "L"],
        temperature: ["hot", "cold"],
        sweetness: ["low", "normal"],
        ingredients: ["Bột matcha", "Sữa tươi", "Sữa đặc"],
        images: ["1752854258679-722872186.webp"], // Sử dụng tên file có sẵn
        stock: 100,
        isAvailable: true,
        preparationTime: 5,
        calories: 180,
        isFeatured: true,
        createdBy: adminUser._id,
      },
      {
        name: "Cappuccino",
        description: "Espresso đậm đà kết hợp với bọt sữa mịn màng",
        price: 35000,
        category: "coffee",
        size: ["M", "L"],
        temperature: ["hot"],
        sweetness: ["none", "low"],
        ingredients: ["Espresso", "Sữa tươi"],
        images: ["1752854258688-123536367.webp"],
        stock: 100,
        isAvailable: true,
        preparationTime: 4,
        calories: 120,
        isFeatured: false,
        createdBy: adminUser._id,
      },
      {
        name: "Trà đào cam sả",
        description: "Hương vị tươi mát của đào, cam kết hợp với sả thơm",
        price: 42000,
        category: "tea",
        size: ["M", "L"],
        temperature: ["cold"],
        sweetness: ["low", "normal", "high"],
        ingredients: ["Trà", "Đào", "Cam", "Sả"],
        images: ["1752854270270-897946032.webp"],
        stock: 100,
        isAvailable: true,
        preparationTime: 5,
        calories: 110,
        isFeatured: false,
        createdBy: adminUser._id,
      },

      // Thêm sản phẩm Coffee
      {
        name: "Americano",
        description:
          "Espresso pha loãng với nước nóng, hương vị đậm đà thanh thoát",
        price: 32000,
        category: "coffee",
        size: ["M", "L"],
        temperature: ["hot", "cold"],
        sweetness: ["none"],
        ingredients: ["Espresso", "Nước"],
        images: ["1752854270283-731448442.webp"],
        stock: 100,
        isAvailable: true,
        preparationTime: 3,
        calories: 5,
        isFeatured: false,
        createdBy: adminUser._id,
      },
      {
        name: "Latte",
        description:
          "Espresso kết hợp hoàn hảo với sữa tươi và lớp foam mềm mại",
        price: 38000,
        category: "coffee",
        size: ["M", "L"],
        temperature: ["hot", "cold"],
        sweetness: ["none", "low"],
        ingredients: ["Espresso", "Sữa tươi"],
        images: ["1752854294418-112345846.webp"],
        stock: 100,
        isAvailable: true,
        preparationTime: 4,
        calories: 140,
        isFeatured: false,
        createdBy: adminUser._id,
      },
      {
        name: "Mocha",
        description:
          "Sự kết hợp tuyệt vời giữa espresso, chocolate và sữa tươi",
        price: 42000,
        category: "coffee",
        size: ["M", "L"],
        temperature: ["hot", "cold"],
        sweetness: ["low", "normal"],
        ingredients: ["Espresso", "Chocolate", "Sữa tươi"],
        images: ["1752854294427-144798697.webp"],
        stock: 100,
        isAvailable: true,
        preparationTime: 5,
        calories: 200,
        isFeatured: false,
        createdBy: adminUser._id,
      },

      // Sản phẩm A-Mê (Đồ uống đặc biệt)
      {
        name: "A-Mê Dâu Tây",
        description: "Đồ uống độc đáo với hương vị dâu tây tươi mát",
        price: 45000,
        category: "a-me",
        size: ["M", "L"],
        temperature: ["cold"],
        sweetness: ["normal", "high"],
        ingredients: ["Dâu tây", "Sữa", "Syrup"],
        images: ["1752854305754-261275349.webp"],
        stock: 100,
        isAvailable: true,
        preparationTime: 6,
        calories: 180,
        isFeatured: true,
        createdBy: adminUser._id,
      },
      {
        name: "A-Mê Xoài",
        description: "Hương vị xoài chín ngọt ngào, đậm đà khó quên",
        price: 45000,
        category: "a-me",
        size: ["M", "L"],
        temperature: ["cold"],
        sweetness: ["normal", "high"],
        ingredients: ["Xoài", "Sữa", "Syrup"],
        images: ["1752854305763-527425275.webp"],
        stock: 100,
        isAvailable: true,
        preparationTime: 6,
        calories: 190,
        isFeatured: false,
        createdBy: adminUser._id,
      },
      {
        name: "A-Mê Chocolate",
        description: "Đồ uống chocolate đậm đà với topping kem tươi",
        price: 48000,
        category: "a-me",
        size: ["M", "L"],
        temperature: ["cold", "hot"],
        sweetness: ["normal", "high"],
        ingredients: ["Chocolate", "Sữa", "Kem tươi"],
        images: ["1752854318341-847276463.webp"],
        stock: 100,
        isAvailable: true,
        preparationTime: 7,
        calories: 220,
        isFeatured: false,
        createdBy: adminUser._id,
      },

      // Sản phẩm Hi-Tea
      {
        name: "Hi-Tea Chanh Dây",
        description: "Trà chanh dây chua ngọt tươi mát, bổ sung vitamin C",
        price: 39000,
        category: "hi-tea",
        size: ["M", "L"],
        temperature: ["cold"],
        sweetness: ["low", "normal", "high"],
        ingredients: ["Trà", "Chanh dây", "Mật ong"],
        images: ["1752854318349-113155515.webp"],
        stock: 100,
        isAvailable: true,
        preparationTime: 5,
        calories: 120,
        isFeatured: false,
        createdBy: adminUser._id,
      },
      {
        name: "Hi-Tea Dâu",
        description: "Trà dâu tây thơm ngon với các miếng dâu tươi",
        price: 42000,
        category: "hi-tea",
        size: ["M", "L"],
        temperature: ["cold"],
        sweetness: ["normal", "high"],
        ingredients: ["Trà", "Dâu tây", "Syrup"],
        images: ["1752854336267-430848559.webp"],
        stock: 100,
        isAvailable: true,
        preparationTime: 5,
        calories: 140,
        isFeatured: false,
        createdBy: adminUser._id,
      },
      {
        name: "Hi-Tea Olong",
        description: "Trà ô long thượng hạng với hương thơm đặc trưng",
        price: 35000,
        category: "hi-tea",
        size: ["M", "L"],
        temperature: ["hot", "cold"],
        sweetness: ["none", "low"],
        ingredients: ["Trà Ô long"],
        images: ["1752854336279-492184050.webp"],
        stock: 100,
        isAvailable: true,
        preparationTime: 4,
        calories: 0,
        isFeatured: false,
        createdBy: adminUser._id,
      },

      // Thêm sản phẩm Matcha
      {
        name: "Matcha Đá Xay",
        description: "Matcha đá xay mát lạnh với topping kem tươi",
        price: 52000,
        category: "matcha",
        size: ["M", "L"],
        temperature: ["cold"],
        sweetness: ["low", "normal"],
        ingredients: ["Bột matcha", "Đá", "Kem tươi", "Sữa"],
        images: ["1752854376179-88302734.webp"],
        stock: 100,
        isAvailable: true,
        preparationTime: 6,
        calories: 200,
        isFeatured: false,
        createdBy: adminUser._id,
      },
      {
        name: "Matcha Cheesecake",
        description: "Đồ uống matcha kết hợp với hương vị cheesecake độc đáo",
        price: 55000,
        category: "matcha",
        size: ["M", "L"],
        temperature: ["cold"],
        sweetness: ["normal"],
        ingredients: ["Bột matcha", "Cream cheese", "Sữa tươi"],
        images: ["1752854376191-988190245.webp"],
        stock: 100,
        isAvailable: true,
        preparationTime: 7,
        calories: 240,
        isFeatured: false,
        createdBy: adminUser._id,
      },
      {
        name: "Matcha Macchiato",
        description: "Matcha latte với lớp macchiato đặc biệt",
        price: 48000,
        category: "matcha",
        size: ["M", "L"],
        temperature: ["hot", "cold"],
        sweetness: ["low", "normal"],
        ingredients: ["Bột matcha", "Espresso", "Sữa tươi"],
        images: ["1752854402456-207925304.webp"],
        stock: 100,
        isAvailable: true,
        preparationTime: 5,
        calories: 180,
        isFeatured: false,
        createdBy: adminUser._id,
      },

      // Sản phẩm Cake (Bánh mặn và ngọt)
      {
        name: "Bánh Croissant Bơ",
        description: "Bánh croissant bơ thơm ngon, giòn tan",
        price: 25000,
        category: "cake",
        size: ["M"],
        temperature: ["room"],
        sweetness: ["low"],
        ingredients: ["Bột mì", "Bơ", "Trứng"],
        images: ["1752854402465-591558858.webp"],
        stock: 50,
        isAvailable: true,
        preparationTime: 2,
        calories: 280,
        isFeatured: false,
        createdBy: adminUser._id,
      },
      {
        name: "Bánh Tiramisu",
        description: "Bánh tiramisu Italia chuẩn vị với mascarpone",
        price: 38000,
        category: "cake",
        size: ["M"],
        temperature: ["cold"],
        sweetness: ["normal"],
        ingredients: ["Mascarpone", "Cà phê", "Ladyfinger", "Cocoa"],
        images: ["1752854415406-37824234.webp"],
        stock: 30,
        isAvailable: true,
        preparationTime: 3,
        calories: 320,
        isFeatured: false,
        createdBy: adminUser._id,
      },
      {
        name: "Bánh Cheesecake Dâu",
        description: "Bánh cheesecake mềm mịn với topping dâu tây tươi",
        price: 42000,
        category: "cake",
        size: ["M"],
        temperature: ["cold"],
        sweetness: ["normal"],
        ingredients: ["Cream cheese", "Dâu tây", "Bánh quy"],
        images: ["1752854415415-459441175.webp"],
        stock: 25,
        isAvailable: true,
        preparationTime: 3,
        calories: 350,
        isFeatured: false,
        createdBy: adminUser._id,
      },
      {
        name: "Bánh Mì Sandwich",
        description: "Bánh mì sandwich thịt nguội, rau củ tươi ngon",
        price: 35000,
        category: "cake",
        size: ["M"],
        temperature: ["room"],
        sweetness: ["none"],
        ingredients: ["Bánh mì", "Thịt nguội", "Rau củ", "Sốt"],
        images: ["1752854448810-456606988.webp"],
        stock: 40,
        isAvailable: true,
        preparationTime: 5,
        calories: 280,
        isFeatured: false,
        createdBy: adminUser._id,
      },
      {
        name: "Bánh Muffin Chocolate",
        description: "Bánh muffin chocolate chip thơm ngon, mềm xốp",
        price: 28000,
        category: "cake",
        size: ["M"],
        temperature: ["room"],
        sweetness: ["normal"],
        ingredients: ["Bột mì", "Chocolate chip", "Trứng", "Bơ"],
        images: ["1752854448818-681604825.webp"],
        stock: 35,
        isAvailable: true,
        preparationTime: 2,
        calories: 250,
        isFeatured: false,
        createdBy: adminUser._id,
      },

      // Thêm một số sản phẩm Tea khác
      {
        name: "Trà Sữa Thái",
        description: "Trà sữa Thái lan đậm đà với hương vị đặc trưng",
        price: 38000,
        category: "tea",
        size: ["M", "L"],
        temperature: ["cold"],
        sweetness: ["normal", "high"],
        ingredients: ["Trà Thái", "Sữa đặc", "Đường"],
        images: ["1752854463312-960422896.webp"],
        stock: 100,
        isAvailable: true,
        preparationTime: 4,
        calories: 180,
        isFeatured: false,
        createdBy: adminUser._id,
      },
      {
        name: "Trà Gạo Rang",
        description: "Trà gạo rang thơm nutty, ít caffeine, tốt cho sức khỏe",
        price: 32000,
        category: "tea",
        size: ["M", "L"],
        temperature: ["hot", "cold"],
        sweetness: ["none", "low"],
        ingredients: ["Trà gạo rang"],
        images: ["1752854463320-929004397.webp"],
        stock: 100,
        isAvailable: true,
        preparationTime: 3,
        calories: 10,
        isFeatured: false,
        createdBy: adminUser._id,
      },
    ];

    // Insert drinks
    await Drink.insertMany(drinks);
    console.log("Sample drinks created successfully");

    console.log("Database initialization completed!");
    console.log("Admin login credentials:");
    console.log("Email: admin@eclipse.com");
    console.log("Password: admin123456");
  } catch (error) {
    console.error("Error initializing database:", error);
  } finally {
    // Close database connection
    await mongoose.connection.close();
  }
};

// Run the initialization
initializeDatabase();
